### ISSUE TITLE
[bug] smh

### ISSUE THREAD

**Issue by Motzumoto** [Fl3t/NitroGenerator#1]
at least put something in the fucking readme instead of the description. Theres literally no instructions on how to even use the script .

**Comment by VrickyStarson** [comment]
> at least put something in the fucking readme instead of the description. Theres literally no instructions on how to even use the script .

Have you found any useful source for generating and checking, if so can you shoot me a friend request on discord Vrickyc#0060, Have a great day.

**Comment by TriangularDev** [comment]
Is it that hard to run a single python script.

**Comment by Motzumoto** [comment]
> Is it that hard to run a single python script.

homie this was a year ago
