### ISSUE TITLE
Broken code.

### ISSUE THREAD

**Issue by 4soobs** [Fl3t/NitroGenerator#3]
I gotta tell you, delete this code, rewerite the whole thing. I tried this thing. (Yes, I installed requests, etc.) But it just keeps erroring and it will just take a while to fix the code and it's syntax errors. I recommend rewriting the script in JS/Node.js. 

@Fl3t

**Comment by ghost** [comment]
Running fine on my end . my question is who the fuck do you think you are telling someone to delete the code and fix the damn errors If you feel that the script should be in  script in JS/Node.js than get up and learn yourself SMH stupid people just wanna bitch when something they DIDNT CODE has errors did you make the script ? N0 did you actuaslly show any errors you have? NO .. what do you think he is here to serve you and do everything you beg for when its 10000000000% Free

**Comment by 4soobs** [comment]
First of all, I am telling the dev to fix the code.
Second of all, I am learning JS and Node myself, aswell making Discord bots.
And you don't need to be so harsh in your comments! @XxHailHydraxX

**Comment by ghost** [comment]
still dosent matter you started it by this stupid first sentence it was disrespectful as fuck .......  but till you know how to make it amd code it never disrespect someone that worked hard on it ..... just becasue it didnt work for you doesnt mean its not working for anyone else . so people find the repo and see issue  saying broken code and they may leave due to an error on you or your computer ................................

 that's what your not getting i guess you never spent hours coding it and testing it ..............

so please till you learn how to code never tell someone to delete there code and rebuild it

**Comment by 4soobs** [comment]
But it's not disrespectful!

It's dev's job, not user's to fix the code, make it cleaner and better!
Rather than saying the dev's jobs as a programmer, you need to watch your sentences, because what you said is also disrespectful and rude, especially with the swear words.

Now, to top this conversation off, do you even know how it is to actually develop a program and fix the bugs, etc.?

@XxHailHydraxX

**Comment by ghost** [comment]
Yes! Python & Ruby and a little of RUST

 you do realize what OPEN SOURCE means?? 

so if there is issues or problems you CAN fix without having  to decompile or unpack or crack ....

So its not the devs job to fix errors they crated the code and posted 


He is making $0.00 ...... now if you bought it off him than yes ITS HIS JOB


i get it your new to all this and in time youll learn the lingo and how GITHUB works .... SO good luck  wish you the best when you learn it

**Comment by ghost** [comment]
this is basically a template to add or change or code or fix to your own preferences and needs


like i said your new and you dont understand it ..and im done so good luck With learning how to code

**Comment by 4soobs** [comment]
You have to learn more about the development, it's responsibilities, Github, and not to use swear words in comments.

As you ruined the whole issue, and this isn't an issue, but drama, created by you, I shall close the issue.

Hope you not have a good day.

**Comment by shakealeg** [comment]
> I gotta tell you, delete this code, rewerite the whole thing. I tried this thing. (Yes, I installed requests, etc.) But it just keeps erroring and it will just take a while to fix the code and it's syntax errors. I recommend rewriting the script in JS/Node.js.
> 
> @Fl3t

Javascript is garbage for anything unless it's web development. And who are you telling someone to rewrite their code, you do it yourself. He doesn't have to comply.

**Comment by shakealeg** [comment]
> First of all, I am telling the dev to fix the code. Second of all, I am learning JS and Node myself, aswell making Discord bots. And you don't need to be so harsh in your comments! @XxHailHydraxX

"telling" Grow the f*** up. Learn manners and stop trying to boss someone around.

**Comment by shakealeg** [comment]
> But it's not disrespectful!
> 
> It's dev's job, not user's to fix the code, make it cleaner and better! Rather than saying the dev's jobs as a programmer, you need to watch your sentences, because what you said is also disrespectful and rude, especially with the swear words.
> 
> Now, to top this conversation off, do you even know how it is to actually develop a program and fix the bugs, etc.?
> 
> @XxHailHydraxX

What a dumb sentence. If the developer isn't being paid, they don't have to do jack sh*t. This is Github, both developers and community fix code together. You are disrespectful for trying to force the developer to do work for you.

**Comment by shakealeg** [comment]
> You have to learn more about the development, it's responsibilities, Github, and not to use swear words in comments.
> 
> As you ruined the whole issue, and this isn't an issue, but drama, created by you, I shall close the issue.
> 
> Hope you not have a good day.

You do you idiot. GITHUB IS MADE FOR THE COMMUNITY, NOT JUST FOR BIG GAMING STUDIOS TO POST CODE TO PUBLIC DOMAIN.
This issue was never relevant. That's your fault.
Get off and learn what the term "FOSS" means and what "Git" was made for.

**Comment by 4soobs** [comment]
> > You have to learn more about the development, it's responsibilities, Github, and not to use swear words in comments.
> > As you ruined the whole issue, and this isn't an issue, but drama, created by you, I shall close the issue.
> > Hope you not have a good day.
> 
> You do you idiot. GITHUB IS MADE FOR THE COMMUNITY, NOT JUST FOR BIG GAMING STUDIOS TO POST CODE TO PUBLIC DOMAIN. This issue was never relevant. That's your fault. Get off and learn what the term "FOSS" means and what "Git" was made for.

i even forgot what this was about, this is over a 2 year old thread now 😭
